### ISSUE TITLE
App crashes if on attempts to register an existing user

### ISSUE THREAD

**Issue by edenismine** [devslopes-learn/mac-chat-api#18]
Getting the following error if I try to register a user twice.

```javascript
_http_outgoing.js:503
    throw new errors.Error('ERR_HTTP_HEADERS_SENT', 'set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at validateHeader (_http_outgoing.js:503:11)
    at ServerResponse.setHeader (_http_outgoing.js:510:3)
    at ServerResponse.header (/mnt/d/Developing/mac-chat-api/node_modules/express/lib/response.js:725:10)
    at ServerResponse.send (/mnt/d/Developing/mac-chat-api/node_modules/express/lib/response.js:170:12)
    at /mnt/d/Developing/mac-chat-api/src/controller/account.js:28:31
    at complete (/mnt/d/Developing/mac-chat-api/node_modules/passport/lib/middleware/authenticate.js:250:13)
    at /mnt/d/Developing/mac-chat-api/node_modules/passport/lib/middleware/authenticate.js:257:15
    at pass (/mnt/d/Developing/mac-chat-api/node_modules/passport/lib/authenticator.js:421:14)
    at Authenticator.transformAuthInfo (/mnt/d/Developing/mac-chat-api/node_modules/passport/lib/authenticator.js:443:5)
    at /mnt/d/Developing/mac-chat-api/node_modules/passport/lib/middleware/authenticate.js:254:22
    at IncomingMessage.req.login.req.logIn (/mnt/d/Developing/mac-chat-api/node_modules/passport/lib/http/request.js:63:13)
    at Strategy.strategy.success (/mnt/d/Developing/mac-chat-api/node_modules/passport/lib/middleware/authenticate.js:235:13)
    at verified (/mnt/d/Developing/mac-chat-api/node_modules/passport-local/lib/strategy.js:83:10)
    at PBKDF2.ondone (/mnt/d/Developing/mac-chat-api/node_modules/passport-local-mongoose/index.js:152:16)
```

Postman returns:

```javascript
{
    "message": {
        "name": "UserExistsError",
        "message": "A user with the given username is already registered"
    }
}
```

if the following POST is sent multiple times to `http://localhost:3005/v1/account/register`:

```javascript
{
  "email": "j@j.com",
  "password": "123456"
}
```

**Comment by SerialAnonymous** [comment]
please tell me the solution for this same issue

**Comment by cemck** [comment]
i think this fixes the problem:
in your mac-chat-api/src/controller/account.js change the code block in line 15-33 to this:
```javascript
// '/v1/account/register'
  api.post('/register', (req, res) => {
    UserDataExt.findUserByEmail(req.body.email, (err, userData) => {
      if (err) {
        res.status(409).json({ message: `An error occured: ${err.message}`});
      } else if (userData) {
        res.status(300).json({ message: `Email ${req.body.email} is already registered`});
      } else {
        Account.register(new Account({ username: req.body.email }), req.body.password, function(err, account) {
          if(err) {
            res.status(500).json({ message: err });
          } else {
            passport.authenticate('local', { session: false })(req, res, () => {
              res.status(200).send('Successfully created new account');
            });
          }
        });
      }
    });
  });
```

**Comment by ghost** [comment]
Hey there, thanks for this. I know this hasn't been a very maintained repo.  I will take a look at the registration issue to avoid some of these headaches.
